spring:
  cloud:
    vault:
      uri: ${VAULT_URI}
      authentication: ${VAULT_AUTHENTICATION}
      kubernetes:
        role: ${VAULT_KUBERNETES_ROLE}
        mount-path: ${VAULT_KUBERNETES_MOUNT_PATH}
      kv:
        enabled: ${VAULT_KV_ENABLED}
        backend: ${VAULT_KV_BACKEND}
        default-context: ${VAULT_KV_DEFAULT_CONTEXT}
