apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-bybit-connector-app-config
data:
  application.yml: |
    spring:
      cloud:
        vault:
          uri: "{{ index .Values.env.vault.uri }}"
          authentication: "{{ index .Values.env.vault.authentication }}"
          kubernetes:
            role: "{{ index .Values.env.vault.kubernetes.role }}"
            mount-path: "{{ index .Values.env.vault.kubernetes.mount-path }}"
          kv:
            enabled: {{ index .Values.env.vault.kv.enabled }}
            backend: "{{ index .Values.env.vault.kv.backend }}"
            default-context: "{{ index .Values.env.vault.default-context }}"

