apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-bybit-connector-app-config
data:
  VAULT_URI: "http://vault.vault.svc.cluster.local:8200"
  VAULT_AUTHENTICATION: "Kubernetes"
  VAULT_KUBERNETES_ROLE: "spring-app"
  VAULT_KUBERNETES_MOUNT_PATH: "auth/kubernetes"
  VAULT_KV_ENABLED: "true"
  VAULT_KV_BACKEND: "secret"
  VAULT_KV_DEFAULT_CONTEXT: "bybit"
