apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-bybit-connector-app
  labels:
    app: spring-bybit-connector-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-bybit-connector-app
  template:
    metadata:
      labels:
        app: spring-bybit-connector-app
    spec:
      containers:
        - name: spring-bybit-connector-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-bybit-connector-app-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
