replicaCount: 1

image:
  repository: spring-bybit-connector-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: spring-bybit-connector-app
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  vault:
    uri: http://vault.vault.svc.cluster.local:8200
    authentication: Kubernetes
    kubernetes:
      role: spring-app
      mount-path: auth/kubernetes
    kv:
      enabled: true
      backend: secret
      default-context: bybit

resources: {}

