namespace: local-dev

images:
  zookeeper: zookeeper:3.9.2
  kafka: apache/kafka:3.7.0
  springApp: local/spring-kafka-sender:latest

kafka:
  replicas: 1
  brokerId: 1
  listeners:
    internal: INTERNAL://:9092
    external: EXTERNAL://:9094
  cfg:
    num.partitions: 1
    default.replication.factor: 1
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1

zookeeper:
  clientPort: 2181

springApp:
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: local
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: kafka:9092
    - name: SPRING_KAFKA_TOPIC
      value: demo
  service:
    type: ClusterIP
    port: 8080
